// AUTO-GENERATED by scripts/gen-manpower.js — do not edit by hand.
// Source workbook: Manpower work Details Sheet 2026-08-31.xlsx
// Manpower is baked in (not fetched live). To refresh, re-run:
//   node scripts/gen-manpower.js "<path to the latest manpower .xlsx>"
module.exports = {
  "date": "2026-08-31",
  "mobilized": [
    {
      "category": "Site Manager",
      "foreigner": 1,
      "otherNepali": 0,
      "localNepali": 0,
      "total": 1
    },
    {
      "category": "Manager/Chief Engineer",
      "foreigner": 6,
      "otherNepali": 4,
      "localNepali": 0,
      "total": 10
    },
    {
      "category": "Engineer",
      "foreigner": 14,
      "otherNepali": 27,
      "localNepali": 20,
      "total": 61
    },
    {
      "category": "Admin/Account",
      "foreigner": 4,
      "otherNepali": 7,
      "localNepali": 11,
      "total": 22
    },
    {
      "category": "Foreman",
      "foreigner": 17,
      "otherNepali": 10,
      "localNepali": 4,
      "total": 31
    },
    {
      "category": "Skilled Labor",
      "foreigner": 0,
      "otherNepali": 69,
      "localNepali": 226,
      "total": 295
    },
    {
      "category": "Semi-skilled Labor",
      "foreigner": 0,
      "otherNepali": 0,
      "localNepali": 10,
      "total": 10
    },
    {
      "category": "Unskilled Labor",
      "foreigner": 0,
      "otherNepali": 1,
      "localNepali": 95,
      "total": 96
    },
    {
      "category": "Operator/Driver",
      "foreigner": 0,
      "otherNepali": 17,
      "localNepali": 93,
      "total": 110
    },
    {
      "category": "Others",
      "foreigner": 0,
      "otherNepali": 10,
      "localNepali": 50,
      "total": 60
    }
  ],
  "mobilizedTotal": {
    "foreigner": 42,
    "otherNepali": 145,
    "localNepali": 509,
    "total": 696
  },
  "idle": [
    {
      "category": "Skilled Labor",
      "foreigner": 0,
      "otherNepali": 5,
      "localNepali": 6,
      "total": 11
    },
    {
      "category": "Semi-skilled Labor",
      "foreigner": 0,
      "otherNepali": 0,
      "localNepali": 2,
      "total": 2
    },
    {
      "category": "Operator/Driver",
      "foreigner": 0,
      "otherNepali": 2,
      "localNepali": 6,
      "total": 8
    }
  ],
  "idleTotal": {
    "foreigner": 0,
    "otherNepali": 7,
    "localNepali": 14,
    "total": 21
  },
  "locations": [
    {
      "name": "Office",
      "foreigner": 20,
      "otherNepali": 39,
      "localNepali": 50,
      "total": 109
    },
    {
      "name": "Powerhouse Area",
      "foreigner": 5,
      "otherNepali": 30,
      "localNepali": 196,
      "total": 231
    },
    {
      "name": "Adit-4",
      "foreigner": 3,
      "otherNepali": 22,
      "localNepali": 16,
      "total": 41
    },
    {
      "name": "Adit-3",
      "foreigner": 2,
      "otherNepali": 28,
      "localNepali": 58,
      "total": 88
    },
    {
      "name": "Adit-2",
      "foreigner": 2,
      "otherNepali": 7,
      "localNepali": 57,
      "total": 66
    },
    {
      "name": "Adit-1 (Headworks & Gongar)",
      "foreigner": 10,
      "otherNepali": 26,
      "localNepali": 146,
      "total": 182
    }
  ]
};
